### PR TITLE
add slider section

### LINKED ISSUE #6: Add slider section in home
- Add images slider in home section
- Use previous year images for that
- Responsive

### PR DESCRIPTION
**Pull request by krishna-sudo**
fixed: #6 
- fixed slider issue
please review.

### CODE REVIEW

**Comment by kashyapm-wmt** [comment]
@krishna-sudo  The slider is not responsive.
Overlapping with text

**Comment by php5-webmob** [comment]
@krishna-sudo 
In responsive design, the registration link should be below the image. Hacktober logo should be at the top. Use flex order for same

**Comment by kashyapm-wmt** [comment]
@krishna-sudo Add also increase interval duration to 5 seconds.

**Comment by kashyapm-wmt** [comment]
@krishna-sudo On hover change button color

**Pull request merged**
